### ISSUE TITLE
Support other URLs than HTTP

### ISSUE THREAD

**Issue by dgoetz** [LordHepipud/icinga2-powershell-module#13]
If the IE is not allowed to download files, the script fails with a message that it can not install the agent. Also providing a local URL will not fix this. Support for other protocols like FTP/SFTP could be a solution for such environments.

**Comment by LordHepipud** [comment]
I assume #16 would be a solution as well? During my research I realised that even FTP by using system environments will fetch the config from the IE, making this step hard to resolve.

Any objections?

**Comment by dgoetz** [comment]
A file system local URL would only solve half of the problem as it will still require some additional preparation like mounting a share or copying the msi. How is windows handling a smb/cifs URL? This could allow to provide it on a share without the need to mount and could be provided from the icinga server if required.

**Comment by LordHepipud** [comment]
As this issue is still open: In general providing the simple 'URL' of the share should resolve the problem.

If the user privileged to execute the module can connect to a remote share over the Network, you could add

```
$icinga = Icinga2AgentModule -DownloadUrl '\\storage.example.com\MyShare\Monitoring\Icinga2AgentMSI\'
```
Would this resolve your issue?
FTP would not be an option in case HTTP is failing, as the handler for both requests would require to allow external connections. The share connection however is handeled differently.

Please give me a short feedback if this resolves this issue. Otherwise we have to take a look for another option which I'm not sure exists.

**Comment by dgoetz** [comment]
Yes, this is fine as it seems to be the only valid option for systems not allowing downloading via policy.
