### ISSUE TITLE
Parameter DirectorHostObject should accept object instead of string

### ISSUE THREAD

**Issue by Hipska** [LordHepipud/icinga2-powershell-module#20]
Doing this, the scripts can be created this way:
```powershell
$DirectorHostObject = @{
    'object_name' = '&hostname_placeholder&'
    'object_type' = 'object'
    'imports'     = ('import1','import2')
}

$icinga = Icinga2AgentModule -DirectorHostObject $DirectorHostObject
```
And internally, you could use `ConvertTo-Json -Compress` to get the actual JSON string to be sent to Director.

**Comment by LordHepipud** [comment]
Thank you for the Input. I'm aware of this, but `ConvertTo-Json` is available on PowerShell version 3.x+ only.
Systems running PowerShell 2 (like Windows 2008 / 2008R2) will be unable to use the script then and I'm aware of plenty of people who require PowerShell 2 support for the script.

For that reason I cannot implement it that way, even though it would be a way better implementation and alot more readable.

If there is another way available working with PowerShell version 2 im open for input.

**Comment by Hipska** [comment]
Okay, didn't know that it was not supported on W2008.

But you could accept both, so you maintain backward compatibility?

**Comment by LordHepipud** [comment]
Honestly I do not want to allow both ways for the same argument, as the result might get more complex in first place.

If you wish to achieve your goal you can still do the following:

DirectorHostObject = @{
    'object_name' = '&hostname_placeholder&'
    'object_type' = 'object'
    'imports'     = ('import1','import2')
}

$icinga = Icinga2AgentModule -DirectorHostObject (ConvertTo-Json -Compress $DirectorHostObject)

This way it makes it easier for newer PowerShell Versions to receive the JSON String and to add it as argument to the module.

Wouldn't this be a good way as well?

**Comment by Hipska** [comment]
Doing this already, but would have been nicer if the module does that by itself ;-)

**Comment by LordHepipud** [comment]
I made some research on this and it is not possible to properly support both ways to generate the host object. In one way or another the module will throw an exception either because the object type is not valid or because the function is not supported.

My proposal for manually doing this is the best option for this case. I will extend the documentation to provide an example.

**Comment by Hipska** [comment]
Not with the same parameter indeed. Maybe a second parameter that accepts an object could be added?

**Comment by LordHepipud** [comment]
I took another look in this request and unfortunately I won't be able to implement this feature. A working code base was to check if the input object is of type 'string' or 'hashtable' and then determine in addition which mayor version of the PowerShell console currently is beeing used.

If the object was a hashtable and atleast PowerShell Version 3, the conversion from the object a JSON-String worked just fine.

Now the problem: Because of the way the PowerShell module is designed and how I handle argument's, I wont be able to hand over proper hashtable objects to the code for later usage. That causes the module to 'corrupt' the content, making it impossible for the ConvertTo-Json function to return proper JSON.

For that reason I can only advice to use my first proposal on this. I will also add this example to the documentation:

```
$JSONObject= @{
  'address' = '127.0.0.1'
  'object_name' = '&hostname_placeholder&'
  'display_name' = '&hostname_placeholder&'
  'object_type' = 'object'
  'imports' = ('Icinga Agent')
}

$icinga = Icinga2AgentModule -DirectorHostObject (ConvertTo-Json -Compress $JSONObject)
$icinga.installMonitoringComponents();
```

**Comment by LordHepipud** [comment]
Found a way to add the support for this feature request. The argument -DirectorHostObject will now accept  strings, hashtables and arrays. Hashtables and arrays will be converted to string in case the PowerShell Version is 3.x and above, otherwise an error is thrown because ConvertTo-Json is not present on lower versions.
