### ISSUE TITLE
Issue with different powershell versions and case sensitivity

### ISSUE THREAD

**Issue by TheAlcesh** [LordHepipud/icinga2-powershell-module#22]
Hi,

i found an issue with the the attached powershell script to read the local hostname from the powershell.
There is a difference for the results of the command
(Get-WmiObject win32_computersystem).DNSHostName
depending on the installed powershell version.
Example hostname "dummy":
V4.0: dummy
V1.0: DUMMY

We created our monitored devices within Icinga2 completly in lower case.
This causes the script to generate faulty certificates and install a broken Icinga2 Client.
To clean this up, i have to uninstall the client and manualy clean (delete the Icinga2 folder) the "ProgramData" folder - Icinga stores the broken certificates there and uses them for all of the following setup attempts!
Maybe a little bit of cleanup after an error or before each run of the installation script would be nice to have.

For now i resolved this issue, by adding the "toLower()" method to the DNSHostName.

#
    # Ensure we get the hostname or FQDN
    # from the PowerShell to make things more
    # easier
    #
    $installer | Add-Member -membertype ScriptMethod -name 'fetchHostnameOrFQDN' -value {
        if ($this.config('get_agent_fqdn') -And (Get-WmiObject win32_computersystem).Domain) {
            [string]$hostname = (Get-WmiObject win32_computersystem).DNSHostName + '.' + (Get-WmiObject win32_computersystem).Domain;
            $this.setProperty('local_hostname', $hostname);
            $this.info('Setting internal Agent Name to ' + $this.getProperty('local_hostname'));
        } elseif ($this.config('get_agent_name')) {
            [string]$hostname = (Get-WmiObject win32_computersystem).DNSHostName;
            $this.setProperty('local_hostname', $hostname);
            $this.info('Setting internal Agent Name to ' + $this.getProperty('local_hostname'));
        }

        if (-Not $this.getProperty('local_hostname')) {
            $this.warn('You have not specified an Agent Name or turned on to auto fetch this information.');
        }
    }

**Comment by LordHepipud** [comment]
Hello and thank you for the report.

The problem is that I know users who are using upper case values instead of lower case. I'm however wondering on why the output is different from the PowerShell versions. I have done some testing here with different Versions and my output is always lower case (as configured within my system config).

Is the name of your host maybe specified in upper case within the system configuration?

For the cleanup: You can force the module to generate new certificates with the argument

`-ForceCertificateGeneration $TRUE`

Up to that you can achieve your requirement without modifying the script by setting the Agent name manually. In combination with PowerShell commands, it can also be combined with automation:

`-AgentName ((Get-WmiObject win32_computersystem).DNSHostName).toLower()`

Both arguments will result in a lower case agent name and force the certificates to re-create in lower case. The config will then be written correctly as well and the Agent is up and running properly without having it to re-install manually.

I will take a look on the handling with upper / lower cases on different systems and see if there is a proper way of doing this.

**Comment by LordHepipud** [comment]
I have reviewed this issue and I'm unable to reproduce it within my environment.
For easier handling I thought about an additional argument, allowing the transformation of the hostname.

-TransformHostname 0|1|2

0: Default. No change applied
1: Transform hostname to lower case
2: Transform hostname to upper case

Any doubts about this?

**Comment by TheAlcesh** [comment]
Better late than never: Sounds like a good solution. Thanks!
