### ISSUE TITLE
Add switch to change behaviour on error

### ISSUE THREAD

**Issue by rustyricky** [LordHepipud/icinga2-powershell-module#65]
For automatic deployment scenarios it's necessary for us to evaluate exit codes to assert whether a deployment was successful or not.

My proposal:

Add a switch in the error-method which evaluates the -ErrorAction common parameter:
-ErrorAction SilentlyContinue -> Print error with Write-Host
-ErrorAction Continue -> Print the error with Write-Error
-ErrorAction Stop -> Print the error with Write-Error and Exit with an exit code != 0
Optionally:
-ErrorAction Inquire -> For interactive scenarios the user could chose to either continue or stop for each occuring error

I'd be happy to provide pull requests if the idea flies.

**Comment by LordHepipud** [comment]
Hello

Thank you very much for the input. I like the idea in general, but at first we should describe on how the module itself should behave during runtime.

Right now there are sevel notify types:
* Debug
* Notice
* Warning
* Error
* Exception

The last item (Exception) will cause the module to exit with status 1 in case an issue is hit which should not occur. The output of these exceptions is added at the logfile / console output at the end again for easier troubleshooting.

Errors are right now thrown but not handeled as failure, as long as no exception occured. This is simply because an error can happen in case a host is already registered within the Icinga Director for example or basic arguments are missing for certain actions, causing an error on certificate generation for example in case no valid ticket is applied.

Any ideas?

**Comment by rustyricky** [comment]
I'd suggest to let the error-method throw an error code and exit the script.
To handle edge cases we could identify them and sort them into three categories:

* acceptable - cannot impact the end result
The message can be degraded to a warning and the script continues.
* configurable - could possible impact the end result
Per default the message can be degraded to a warning and the script continues.
If a certain switch is set for this edge case or category (e.g. --strict-cert-gen for certificate generation) the warning is escalated to an error and the script exits with an exit code.
* critical - will definitely impact the end result
_I'm not sure if these cases exist as they are probably exceptions anyway._
The message is an error and the script exits with an error code.

An example: If you want to use the token returned by the self-service API and the host is already registered you won't receive the token. So you would expect an error.
If the token doesn't matter this error can be ignored and you want your script to continue.
This would fall into the second category and could be solved using a switch (--strict-api-registration or something).

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
