### ISSUE TITLE
Module doesn't work with new Version 2.10.0

### ISSUE THREAD

**Issue by stevie-sy** [LordHepipud/icinga2-powershell-module#80]
When installing a new Windows satellite with the new Icinga Version 2.10 with the -CAProxy option then we get the error: 

Fatal: Exception calling "generateCertificates" with "0" argument(s): "The argument "-CAProxy" is only supported by Icinga Version 2.8.0 and above."
######## The script encountered several errors during run ########
Fatal: Exception calling "generateCertificates" with "0" argument(s): "The argument "-CAProxy" is only supported by Icinga Version 2.8.0 and above."

it seems the string compare function at line 1756 doesn't work correctly with 2.10. With the icinga Version 2.9.2 ist works.

**Comment by LordHepipud** [comment]
Thank you very much for the input. I will take a look on that and provide a fix shortly.

**Comment by LordHepipud** [comment]
The issue should be fixed now and being live on the master.

Reason:
Versions with multiple digits were interpreted as String by the PowerShell instead of an Integer. This caused the validation to fail for Version 2.10.0 for example. The versions will now be casted as Integer during comparison for correct results.

Thank you again for the report and sorry for the trouble!

**Comment by stevie-sy** [comment]
Thank you for Fixing. I thought something like this with string comparision
