### ISSUE TITLE
Script recognized workgroup as domain

### ISSUE THREAD

**Issue by lazyfrosch** [LordHepipud/icinga2-powershell-module#84]
When a server is not member of an domain, but only a workgroup, the module does not try to resolve a locally configured DNS suffix.

In any way `SERVER.WORKGROUP` is not a useful FQDN.

/cc @R-Sommer

**Comment by LordHepipud** [comment]
I see, this could be a problem. The issue is that

```powershell
(Get-WmiObject win32_computersystem).DNSHostName
```

will return both, Domain or Workgroup as result.

Even

```powershell
(Get-WmiObject win32_computersystem).Domain
```

will return both, as a workgroup is defined as "local" domain.

There is an open pull request, which seems to have fixed this issue by using

```powershell
[System.Net.Dns]::GetHostEntry([string]$env:computername).HostName
```

for fetching the FQDN from the DNS. I know see what the fix was for. On my local machine this returned the `hostname` without the workgroup. On a joined domain windows, the result was hostname + domain.

This should resolve the issue then. Any doubts about this?

**Comment by LordHepipud** [comment]
Just one additional note: The problem is, the above call

```powershell
[System.Net.Dns]::GetHostEntry([string]$env:computername).HostName
```

is not supported by PowerShell version 2. If we wish to implement this, we will break support for PowerShell 2.

I will have a look if there are other options available, because the module itself is in general designed to work with PowerShell 2.x.

If we wish to break that support, we should draft the new release very carefully and possibly catch such functions properly or fully disable 2.0 support,

**Comment by lazyfrosch** [comment]
This seems to be a viable solution as well:

```
> [System.Net.Dns]::GetHostEntry("localhost")

HostName                   Aliases AddressList
--------                   ------- -----------
amalia-win10.lazyfrosch.de {}      {::1, 127.0.0.1}
```

We would only have to split HostName.

Question is: Why doesn't it work in PS2? [DOTNET seems to support it](https://docs.microsoft.com/de-de/dotnet/api/system.net.dns.gethostentry?view=netframework-2.0)

**Comment by lazyfrosch** [comment]
```
PS C:\Windows\system32> powershell.exe -Version 2
Windows PowerShell
Copyright (C) 2009 Microsoft Corporation. Alle Rechte vorbehalten.

PS C:\Windows\system32> [Net.DNS]::GetHostEntry("localhost")
GetHostEntry : Ausnahme beim Aufrufen von "GetHostEntry" mit 1 Argument(en):  "Das Konfigurationssystem konnte nicht initialisiert werden."
Bei Zeile:1 Zeichen:24
+ [Net.DNS]::GetHostEntry <<<< ("localhost")
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException
```

**Comment by LordHepipud** [comment]
Is `lazyfrosch.de` your workgroup or your internal domain? Just asking because on my Windows systems without domain only the hostname is returned.

To fetch the hostname only, you can use this:

```powershell
(Get-WmiObject win32_computersystem).DNSHostName;
```

This will return only the hostname without `Domain` or `Workgroup`

**Comment by R-Sommer** [comment]
My oldest test system is Windows Storage Server 2008 (without R2) and it's working with Powershell V2:
```
PS C:\Users\Administrator> $psversiontable

Name                           Value
----                           -----
CLRVersion                     2.0.50727.8800
BuildVersion                   6.0.6002.18111
PSVersion                      2.0
WSManStackVersion              2.0
PSCompatibleVersions           {1.0, 2.0}
SerializationVersion           1.1.0.1
PSRemotingProtocolVersion      2.1


PS C:\Users\Administrator> [System.Net.Dns]::GetHostByName("localhost")

HostName                                          Aliases                                           AddressList
--------                                          -------                                           -----------
srv1.testnet.lan                 {}                                                {127.0.0.1}


PS C:\Users\Administrator> [System.Net.Dns]::GetHostEntry("localhost")

HostName                                          Aliases                                           AddressList
--------                                          -------                                           -----------
srv1.testnet.lan                 {}                                                {::1, 127.0.0.1}
```
**testnet.lan** is "Primary DNS Suffix of this computer"

**Comment by LordHepipud** [comment]
Is

```
[System.Net.Dns]::GetHostEntry("localhost").HostName
```

working as well on this host? This should be the proper way to do it, as it will return either the `hostname` or the `FQDN` in case a domain is joined.

I'm just wondering on why the command is not working on any of my machines with PS 2

**Comment by R-Sommer** [comment]
I'm not sure if Windows Storage Server is different here (assuming you have "normal" Windows).
```
PS C:\Users\Administrator> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
6      0      6002   131072
```

If a primary DNS Suffix is configured on a standalone machine, the command will return the FQDN:

Windows Storage Server 2008:
```
PS C:\Users\Administrator> [System.Net.Dns]::GetHostEntry("localhost").HostName
srv1.testnet.lan

PS C:\Users\Administrator> (gwmi win32_computersystem).partofdomain
False
```

Looks the identical for a domain member:

Windows 2012 R2:
```
PS C:\temp> $psversiontable

Name                           Value
----                           -----
PSVersion                      4.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.34014
BuildVersion                   6.3.9600.17400
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}
PSRemotingProtocolVersion      2.2

PS C:\temp> [System.Net.Dns]::GetHostEntry("localhost").HostName
IcingaAgentTest.EM.LAN

PS C:\temp> (gwmi win32_computersystem).partofdomain
True
```

**Comment by lazyfrosch** [comment]
I guess we should use `GetHostEntry()` by default then?

Should we avoid `win32_computersystem` and only use proper setting fqdn and short hostname based on the options?

**Comment by LordHepipud** [comment]
I think it depends a little on the user requirement. When I think this entire process through, I would believe the best option would be as follows:

Use

```powershell
(Get-WmiObject win32_computersystem).PartOfDomain
```

to determine if we are part of a Domain or not. In case we are, we should use the FQDN as return value, as we are member of a Domain and therefor the name is correct.

So using

```powershell
[System.Net.Dns]::GetHostEntry("localhost").HostName
```

in addition would result in the proper construct of the name.

In case we are not part of a Domain, I would only want to return the actual hostname, which can be done by using

```powershell
(Get-WmiObject win32_computersystem).DNSHostName
```

So the actual result is identical to every single system.

I do however have the fear, that any change we apply here might break existing setups. So we have to carefully consider on how we want to properly achieve this.

In first place, `my-machine.WORKGROUP` is definately wrong, I'm however unsure if this will break any setup we have already.

Imagine the following:
The module is creating hosts with `my-machine.WORKGROUP` within the Icinga Director - which we agree is wrong. However, changing this behaviour now with a new release, will cause the module to behave differently and in the worst case, create a second Host-Object within the Icinga Director, making the old one obsolete, because the name we configure is also the one written within the Icinga 2 configuration file and stored within the SSL certificates.

I'm open for any idea and if we really consider this as a bug (what we should, as it is), this fix might cause some problems.

I just want everyone to be aware of this.

So the configuration flags would return the following:

**Hostname**

Only the hostname is returned by using

```powershell
(Get-WmiObject win32_computersystem).DNSHostName
```

Output:
```
my-machine
```

**FQDN**

Verification is done by using

```powershell
(Get-WmiObject win32_computersystem).PartOfDomain
```

**Option 1:** Host is part of a domain

Fetch it with

```powershell
[System.Net.Dns]::GetHostEntry("localhost").HostName
```

Output:
```
my-machine.internaldomain.de
```

**Option 2:** Host is **not** part of a domain

```powershell
(Get-WmiObject win32_computersystem).DNSHostName
```

Output:
```
my-machine
```

Have I covered everything up here?

**Comment by R-Sommer** [comment]
I've no idea whether is best to change the default behaviour. However, if you want to avoid this risk, what about defining a new parameter e.g. -HostnameOnly or -NetBIOSName und use **[System.Net.Dns]::GetHostName()** for every case?

**Comment by LordHepipud** [comment]
This could also be an option. I will discuss this with @lazyfrosch after my vacation which approach would be the best.

We will sum up our results in this issue then.

Thank you so far for the great input :)

**Comment by R-Sommer** [comment]
I'd like to put here some more thoughts for your discussion after your vacation:

There are 3 posibilities for a hostname:
1. A domain member
2. Stand-alone with primary DNS suffix
3. Stand-alone without primary DNS suffix

The current behaviour is:
1. FQDN
2. hostname.workgroup
3. hostname.workgroup

Proposed behaviour (which is already default for Icinga 2 setup wizard):
1. FQDN
2. FQDN
3. hostname

To achieve the proposed behavior following commands could be used:
1. `[System.Net.Dns]::GetHostEntry("localhost").HostName`
2. `[System.Net.Dns]::GetHostEntry("localhost").HostName`
3. `[System.Net.Dns]::GetHostEntry("localhost").HostName`

To achieve hostname only option following commands could be used:
1. `[System.Net.Dns]::GetHostName()`
2. `[System.Net.Dns]::GetHostName()`
3. `[System.Net.Dns]::GetHostName()`

To keep the current behaviour (to avoid new issues due to changed default behaviour) these changes could be implemented:
1. nothing to do
2. add new argument e.g. -FQDN (Ignores: -HostnameOnly)
3. add new argument e.g. -HostnameOnly (Ignores: -FQDN)

Using -FQDN:
1. has no impact (as it is already default)
2. use FQDN instead of hostname.workgroup
3. has no impact (as there is no FQDN)

Using -HostnameOnly:
1. use hostname instead of FQDN (if that would make sense in any case)
2. use hostname instead of hostname.workgroup
3. has no impact (as it is already default)

**Comment by lazyfrosch** [comment]
As discussed with @LordHepipud we will:

* Deprecate PS 2, which should be no problem for supported Windows releases
* Using the workgroup as part of the will be "fixed" and we will use the FQDN the system thinks it has (nslookup localhost)

Anyways this should only affect machines in workgroups, where you re-execute the script after installation.

**Comment by LordHepipud** [comment]
As we are moving forward with Icinga for Windows and the PowerShell Framework, we will not continue on this issue.
